services:
  tubentor-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tubentor-backend
    hostname: tubentor-backend
    env_file: "./backend/.env"
    ports:
      - "8000:8000"
    depends_on:
      tubentor-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tubentor-network
    restart: unless-stopped

  tubentor-db:
    image: postgres:17
    container_name: tubentor-db
    hostname: tubentor-db
    env_file: "backend/.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tubentor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped
volumes:
  postgres_data:

networks:
  tubentor-network:
    driver: bridge